export const endpoints = {
  auth: {
    login: '/auth/login',
    sendOtp: '/auth/send-otp',
    verifyOtp: '/auth/verify-otp',
    me: '/auth/me',
  },
  dashboard: {
    summary: '/dashboard/summary',
    owner: '/dashboard/owner',
    operations: '/dashboard/operations',
    finance: '/dashboard/finance',
    dispatch: '/dashboard/dispatch',
    retailer: '/dashboard/retailer',
    driver: '/dashboard/driver',
  },
  retailers: '/retailers',
  salesOrders: '/sales-orders',
  demandConsolidations: '/demand-consolidations',
  purchaseOrders: '/purchase-orders',
  goodsReceipts: '/goods-receipts',
  inventory: '/inventory',
  dispatchTrips: '/dispatch-trips',
  deliveryStops: '/delivery-stops',
  salesInvoices: '/sales-invoices',
  paymentReceipts: '/payment-receipts',
  accounts: '/accounts',
  journals: '/journal-entries',
  reports: '/reports',
} as const;
