import { PrismaClient } from '@prisma/client'
import { IDS, PERMISSIONS, ROLE_PERMISSIONS, SEED_DATES } from './seed-data'

const prisma = new PrismaClient()
const ORG_ID = IDS.organization

/**
 * IMPORTANT:
 * Replace SEED_PASSWORD_HASH with a valid hash generated by your auth service
 * if your login flow verifies passwords using bcrypt/argon2.
 */
const DEFAULT_PASSWORD_HASH =
  process.env.SEED_PASSWORD_HASH ?? 'replace-with-real-password-hash'

async function upsertById(delegate: any, data: Record<string, any>) {
  return delegate.upsert({
    where: { id: data.id },
    update: data,
    create: data,
  })
}

async function seedCoreOrganization() {
  await upsertById(prisma.organization, {
    id: ORG_ID,
    name: 'Sudha Dairy Distributor ERP Demo',
    legalName: 'Sudha Dairy Distributor Patna',
    gstin: '10ABCDE1234F1Z5',
    pan: 'ABCDE1234F',
    phone: '9123456789',
    email: 'owner@sudhadistributor.local',
    timezone: 'Asia/Kolkata',
    currencyCode: 'INR',
    addressJson: {
      line1: 'Boring Road',
      city: 'Patna',
      state: 'Bihar',
      pincode: '800001',
    },
    isActive: true,
  })

  const roles = [
    { id: IDS.roles.owner, organizationId: ORG_ID, code: 'OWNER', name: 'Owner', description: 'Business owner with full control', isSystemRole: true },
    { id: IDS.roles.operationsAdmin, organizationId: ORG_ID, code: 'OPERATIONS_ADMIN', name: 'Operations Admin', description: 'Manages ordering, procurement and dispatch', isSystemRole: true },
    { id: IDS.roles.accountant, organizationId: ORG_ID, code: 'ACCOUNTANT', name: 'Accountant', description: 'Manages finance, ledgers and collections', isSystemRole: true },
    { id: IDS.roles.driver, organizationId: ORG_ID, code: 'DRIVER', name: 'Driver / Delivery Staff', description: 'Runs dispatch and updates deliveries', isSystemRole: true },
    { id: IDS.roles.salesperson, organizationId: ORG_ID, code: 'SALESPERSON', name: 'Salesperson', description: 'Creates assisted orders and manages retailer relations', isSystemRole: true },
    { id: IDS.roles.retailer, organizationId: ORG_ID, code: 'RETAILER', name: 'Retailer', description: 'Retailer portal access', isSystemRole: true },
  ]

  for (const role of roles) await upsertById(prisma.role, role)
  for (const permission of PERMISSIONS) await upsertById(prisma.permission, permission)

  const rolePermissionRows = Object.entries(ROLE_PERMISSIONS).flatMap(([roleId, permissionIds]) =>
    permissionIds.map((permissionId) => ({ roleId, permissionId }))
  )

  await prisma.rolePermission.createMany({ data: rolePermissionRows, skipDuplicates: true })

  const settings = [
    {
      id: '00000000-0000-0000-0000-000000010001',
      organizationId: ORG_ID,
      settingGroup: 'business_rules',
      settingKey: 'default_order_cutoff',
      valueJson: { time: '21:00', appliesTo: 'all_routes' },
      isEncrypted: false,
    },
    {
      id: '00000000-0000-0000-0000-000000010002',
      organizationId: ORG_ID,
      settingGroup: 'invoice',
      settingKey: 'invoice_series',
      valueJson: { prefix: 'INV', nextNumber: 1001 },
      isEncrypted: false,
    },
    {
      id: '00000000-0000-0000-0000-000000010003',
      organizationId: ORG_ID,
      settingGroup: 'assisted_mode',
      settingKey: 'enabled',
      valueJson: { allowAdminOrders: true, allowAdminInvoices: true },
      isEncrypted: false,
    },
  ]

  for (const setting of settings) await upsertById(prisma.systemSetting, setting)
}

async function seedAccountingMasters() {
  const accounts = [
    { id: IDS.accounts.receivables, organizationId: ORG_ID, accountCode: '1100', accountName: 'Trade Receivables', accountType: 'asset', isControlAccount: true, isActive: true },
    { id: IDS.accounts.payables, organizationId: ORG_ID, accountCode: '2100', accountName: 'Trade Payables', accountType: 'liability', isControlAccount: true, isActive: true },
    { id: IDS.accounts.sales, organizationId: ORG_ID, accountCode: '4100', accountName: 'Sales - Dairy Products', accountType: 'income', isControlAccount: false, isActive: true },
    { id: IDS.accounts.purchase, organizationId: ORG_ID, accountCode: '5100', accountName: 'Purchases - Dairy Products', accountType: 'expense', isControlAccount: false, isActive: true },
    { id: IDS.accounts.inventory, organizationId: ORG_ID, accountCode: '1200', accountName: 'Inventory - Dairy Stock', accountType: 'asset', isControlAccount: false, isActive: true },
    { id: IDS.accounts.cash, organizationId: ORG_ID, accountCode: '1300', accountName: 'Cash in Hand', accountType: 'asset', isControlAccount: false, isActive: true },
    { id: IDS.accounts.bank, organizationId: ORG_ID, accountCode: '1310', accountName: 'Bank Account', accountType: 'asset', isControlAccount: false, isActive: true },
    { id: IDS.accounts.deliveryExpense, organizationId: ORG_ID, accountCode: '6100', accountName: 'Delivery / Fuel Expense', accountType: 'expense', isControlAccount: false, isActive: true },
  ]

  for (const account of accounts) {
    await upsertById(prisma.account, {
      parentAccountId: null,
      ...account,
    })
  }

  await upsertById(prisma.bankAccount, {
    id: IDS.bankAccounts.mainBank,
    organizationId: ORG_ID,
    bankName: 'State Bank of India',
    branchName: 'Patna Main',
    accountNoMasked: 'XXXXXX3412',
    ifscCode: 'SBIN0001234',
    accountId: IDS.accounts.bank,
    isDefault: true,
    isActive: true,
  })

  await upsertById(prisma.cashRegister, {
    id: IDS.cashRegisters.mainCash,
    organizationId: ORG_ID,
    name: 'Main Cash Counter',
    accountId: IDS.accounts.cash,
    responsibleUserId: IDS.users.accountant,
    isActive: true,
  })

  await upsertById(prisma.expenseCategory, {
    id: IDS.expenseCategories.fuel,
    organizationId: ORG_ID,
    code: 'FUEL',
    name: 'Fuel Expense',
    accountId: IDS.accounts.deliveryExpense,
    isActive: true,
  })
}

async function seedOperationsMasters() {
  await upsertById(prisma.area, {
    id: IDS.areas.patnaUrban,
    organizationId: ORG_ID,
    code: 'PATNA-URBAN',
    name: 'Patna Urban',
    city: 'Patna',
    state: 'Bihar',
    isActive: true,
  })

  await upsertById(prisma.route, {
    id: IDS.routes.patnaMorning,
    organizationId: ORG_ID,
    areaId: IDS.areas.patnaUrban,
    code: 'PAT-MORNING-01',
    name: 'Patna Morning Route',
    deliveryShift: 'morning',
    defaultCutoffTime: '21:00',
    isActive: true,
  })

  const employees = [
    { id: IDS.employees.owner, organizationId: ORG_ID, employeeCode: 'EMP-001', fullName: 'Rahul Kumar', designation: 'Owner', mobile: '9123456789', email: 'owner@sudhadistributor.local', joiningDate: new Date('2025-01-01'), assignedRouteId: null, isActive: true },
    { id: IDS.employees.operations, organizationId: ORG_ID, employeeCode: 'EMP-002', fullName: 'Aman Singh', designation: 'Operations Manager', mobile: '9123456790', email: 'ops@sudhadistributor.local', joiningDate: new Date('2025-02-01'), assignedRouteId: IDS.routes.patnaMorning, isActive: true },
    { id: IDS.employees.accountant, organizationId: ORG_ID, employeeCode: 'EMP-003', fullName: 'Sonia Gupta', designation: 'Accountant', mobile: '9123456791', email: 'accounts@sudhadistributor.local', joiningDate: new Date('2025-02-15'), assignedRouteId: null, isActive: true },
    { id: IDS.employees.driver1, organizationId: ORG_ID, employeeCode: 'EMP-004', fullName: 'Rakesh Yadav', designation: 'Driver', mobile: '9123456792', joiningDate: new Date('2025-03-01'), drivingLicenseNo: 'BR01-2024-DRIVER-1234', assignedRouteId: IDS.routes.patnaMorning, isActive: true },
    { id: IDS.employees.sales1, organizationId: ORG_ID, employeeCode: 'EMP-005', fullName: 'Pankaj Verma', designation: 'Sales Executive', mobile: '9123456793', joiningDate: new Date('2025-03-15'), assignedRouteId: IDS.routes.patnaMorning, isActive: true },
  ]

  for (const employee of employees) await upsertById(prisma.employee, employee)

  await upsertById(prisma.vehicle, {
    id: IDS.vehicles.van1,
    organizationId: ORG_ID,
    vehicleNo: 'BR01AB1234',
    vehicleType: 'mini_truck',
    capacityCrates: 120,
    capacityWeightKg: '1500.00',
    fuelType: 'diesel',
    ownershipType: 'owned',
    driverEmployeeId: IDS.employees.driver1,
    isActive: true,
  })

  const suppliers = [
    {
      id: IDS.suppliers.sudhaDepot,
      organizationId: ORG_ID,
      supplierCode: 'SUP-SUDHA-01',
      name: 'Sudha Dairy Depot Patna',
      contactPerson: 'Depot Incharge',
      mobile: '9234567890',
      email: 'depot@sudha.example',
      gstin: '10AAACS1234A1Z7',
      pan: 'AAACS1234A',
      paymentTermsDays: 7,
      payableAccountId: IDS.accounts.payables,
      addressJson: { city: 'Patna', locality: 'Depot Area' },
      isActive: true,
    },
  ]

  for (const supplier of suppliers) await upsertById(prisma.supplier, supplier)

  const retailers = [
    {
      id: IDS.retailers.anandStore,
      organizationId: ORG_ID,
      retailerCode: 'RET-001',
      shopName: 'Anand Store',
      ownerName: 'Anand Kumar',
      mobile: '9345678901',
      locality: 'Kankarbagh',
      city: 'Patna',
      state: 'Bihar',
      pincode: '800020',
      gstin: '10ANAND1234F1Z2',
      creditLimit: '15000.00',
      creditDays: 5,
      assignedRouteId: IDS.routes.patnaMorning,
      assignedSalespersonId: IDS.employees.sales1,
      preferredDeliveryStart: '06:00',
      preferredDeliveryEnd: '08:00',
      retailerCategory: 'kirana',
      businessStatus: 'active',
      orderingMode: 'assisted',
      isOrderingEnabled: true,
      isBillingEnabled: true,
      receivableAccountId: IDS.accounts.receivables,
      openingBalance: '0.00',
      notes: 'Orders are generally placed through admin/phone.',
    },
    {
      id: IDS.retailers.guptaSweets,
      organizationId: ORG_ID,
      retailerCode: 'RET-002',
      shopName: 'Gupta Sweets',
      ownerName: 'Suresh Gupta',
      mobile: '9345678902',
      locality: 'Rajendra Nagar',
      city: 'Patna',
      state: 'Bihar',
      pincode: '800016',
      creditLimit: '25000.00',
      creditDays: 7,
      assignedRouteId: IDS.routes.patnaMorning,
      assignedSalespersonId: IDS.employees.sales1,
      preferredDeliveryStart: '05:30',
      preferredDeliveryEnd: '07:00',
      retailerCategory: 'sweet_shop',
      businessStatus: 'active',
      orderingMode: 'hybrid',
      isOrderingEnabled: true,
      isBillingEnabled: true,
      receivableAccountId: IDS.accounts.receivables,
      openingBalance: '0.00',
    },
    {
      id: IDS.retailers.freshMart,
      organizationId: ORG_ID,
      retailerCode: 'RET-003',
      shopName: 'Fresh Mart',
      ownerName: 'Ritu Raj',
      mobile: '9345678903',
      locality: 'Boring Road',
      city: 'Patna',
      state: 'Bihar',
      pincode: '800001',
      creditLimit: '10000.00',
      creditDays: 3,
      assignedRouteId: IDS.routes.patnaMorning,
      assignedSalespersonId: IDS.employees.sales1,
      preferredDeliveryStart: '06:30',
      preferredDeliveryEnd: '08:30',
      retailerCategory: 'booth',
      businessStatus: 'active',
      orderingMode: 'self_service',
      isOrderingEnabled: true,
      isBillingEnabled: true,
      receivableAccountId: IDS.accounts.receivables,
      openingBalance: '0.00',
    },
  ]

  for (const retailer of retailers) await upsertById(prisma.retailer, retailer)

  await upsertById(prisma.retailerDocument, {
    id: IDS.fileAttachments.anandGst,
    organizationId: ORG_ID,
    retailerId: IDS.retailers.anandStore,
    documentType: 'gst',
    fileUrl: 'https://example.com/docs/anand-gst.pdf',
    fileName: 'anand-gst.pdf',
    remarks: 'Sample GST document',
  })

  await prisma.routeRetailer.createMany({
    data: [
      { id: '00000000-0000-0000-0000-000000010101', organizationId: ORG_ID, routeId: IDS.routes.patnaMorning, retailerId: IDS.retailers.anandStore, stopSequence: 1, preferredDeliveryStart: '06:00', preferredDeliveryEnd: '08:00', isActive: true },
      { id: '00000000-0000-0000-0000-000000010102', organizationId: ORG_ID, routeId: IDS.routes.patnaMorning, retailerId: IDS.retailers.guptaSweets, stopSequence: 2, preferredDeliveryStart: '05:30', preferredDeliveryEnd: '07:00', isActive: true },
      { id: '00000000-0000-0000-0000-000000010103', organizationId: ORG_ID, routeId: IDS.routes.patnaMorning, retailerId: IDS.retailers.freshMart, stopSequence: 3, preferredDeliveryStart: '06:30', preferredDeliveryEnd: '08:30', isActive: true },
    ],
    skipDuplicates: true,
  })
}

async function seedUsers() {
  const users = [
    { id: IDS.users.owner, organizationId: ORG_ID, fullName: 'Rahul Kumar', mobile: '9123456789', email: 'owner@sudhadistributor.local', passwordHash: DEFAULT_PASSWORD_HASH, userType: 'owner', employeeId: IDS.employees.owner, preferredLanguage: 'en', isActive: true },
    { id: IDS.users.operations, organizationId: ORG_ID, fullName: 'Aman Singh', mobile: '9123456790', email: 'ops@sudhadistributor.local', passwordHash: DEFAULT_PASSWORD_HASH, userType: 'ops_admin', employeeId: IDS.employees.operations, preferredLanguage: 'en', isActive: true },
    { id: IDS.users.accountant, organizationId: ORG_ID, fullName: 'Sonia Gupta', mobile: '9123456791', email: 'accounts@sudhadistributor.local', passwordHash: DEFAULT_PASSWORD_HASH, userType: 'accountant', employeeId: IDS.employees.accountant, preferredLanguage: 'en', isActive: true },
    { id: IDS.users.driver1, organizationId: ORG_ID, fullName: 'Rakesh Yadav', mobile: '9123456792', passwordHash: DEFAULT_PASSWORD_HASH, userType: 'staff', employeeId: IDS.employees.driver1, preferredLanguage: 'hi', isActive: true },
    { id: IDS.users.sales1, organizationId: ORG_ID, fullName: 'Pankaj Verma', mobile: '9123456793', passwordHash: DEFAULT_PASSWORD_HASH, userType: 'staff', employeeId: IDS.employees.sales1, preferredLanguage: 'hi', isActive: true },
    { id: IDS.users.retailerAnand, organizationId: ORG_ID, fullName: 'Anand Kumar', mobile: '9345678901', passwordHash: DEFAULT_PASSWORD_HASH, userType: 'retailer_user', retailerId: IDS.retailers.anandStore, preferredLanguage: 'hi', isActive: true },
    { id: IDS.users.retailerFreshMart, organizationId: ORG_ID, fullName: 'Ritu Raj', mobile: '9345678903', passwordHash: DEFAULT_PASSWORD_HASH, userType: 'retailer_user', retailerId: IDS.retailers.freshMart, preferredLanguage: 'en', isActive: true },
  ]

  for (const user of users) await upsertById(prisma.user, user)

  await prisma.userRole.createMany({
    data: [
      { userId: IDS.users.owner, roleId: IDS.roles.owner },
      { userId: IDS.users.operations, roleId: IDS.roles.operationsAdmin },
      { userId: IDS.users.accountant, roleId: IDS.roles.accountant },
      { userId: IDS.users.driver1, roleId: IDS.roles.driver },
      { userId: IDS.users.sales1, roleId: IDS.roles.salesperson },
      { userId: IDS.users.retailerAnand, roleId: IDS.roles.retailer },
      { userId: IDS.users.retailerFreshMart, roleId: IDS.roles.retailer },
    ],
    skipDuplicates: true,
  })
}

async function seedCatalog() {
  const brands = [
    { id: IDS.brands.sudha, organizationId: ORG_ID, name: 'Sudha', isActive: true },
  ]
  for (const brand of brands) await upsertById(prisma.brand, brand)

  const categories = [
    { id: IDS.categories.milk, organizationId: ORG_ID, name: 'Milk', parentId: null, isActive: true },
    { id: IDS.categories.curd, organizationId: ORG_ID, name: 'Curd', parentId: null, isActive: true },
    { id: IDS.categories.paneer, organizationId: ORG_ID, name: 'Paneer', parentId: null, isActive: true },
  ]
  for (const category of categories) await upsertById(prisma.productCategory, category)

  const units = [
    { id: IDS.units.litre, organizationId: ORG_ID, code: 'LTR', name: 'Litre', decimalPlaces: 3 },
    { id: IDS.units.packet, organizationId: ORG_ID, code: 'PKT', name: 'Packet', decimalPlaces: 0 },
    { id: IDS.units.gram, organizationId: ORG_ID, code: 'GM', name: 'Gram', decimalPlaces: 0 },
    { id: IDS.units.kg, organizationId: ORG_ID, code: 'KG', name: 'Kilogram', decimalPlaces: 3 },
  ]
  for (const unit of units) await upsertById(prisma.unit, unit)

  const taxCodes = [
    { id: IDS.taxCodes.dairyZero, organizationId: ORG_ID, code: 'GST-0', hsnCode: '0401', gstRate: '0.00', cgstRate: '0.00', sgstRate: '0.00', igstRate: '0.00', isActive: true },
    { id: IDS.taxCodes.dairyFive, organizationId: ORG_ID, code: 'GST-5', hsnCode: '0406', gstRate: '5.00', cgstRate: '2.50', sgstRate: '2.50', igstRate: '5.00', isActive: true },
  ]
  for (const taxCode of taxCodes) await upsertById(prisma.taxCode, taxCode)

  await upsertById(prisma.crateType, {
    id: IDS.crateTypes.milkCrate,
    organizationId: ORG_ID,
    code: 'CRATE-MILK',
    name: 'Standard Milk Crate',
    capacityUnits: 20,
    depositValue: '500.00',
    isActive: true,
  })

  const products = [
    {
      id: IDS.products.tonedMilk,
      organizationId: ORG_ID,
      productCode: 'PROD-MILK-TONED',
      name: 'Sudha Toned Milk',
      brandId: IDS.brands.sudha,
      categoryId: IDS.categories.milk,
      description: 'Daily toned milk supply',
      taxCodeId: IDS.taxCodes.dairyZero,
      isBatchTracked: true,
      isExpiryTracked: true,
      isReturnable: true,
      defaultCrateTypeId: IDS.crateTypes.milkCrate,
      status: 'active',
    },
    {
      id: IDS.products.dahi,
      organizationId: ORG_ID,
      productCode: 'PROD-DAHI',
      name: 'Sudha Fresh Dahi',
      brandId: IDS.brands.sudha,
      categoryId: IDS.categories.curd,
      taxCodeId: IDS.taxCodes.dairyZero,
      isBatchTracked: true,
      isExpiryTracked: true,
      isReturnable: true,
      status: 'active',
    },
    {
      id: IDS.products.paneer,
      organizationId: ORG_ID,
      productCode: 'PROD-PANEER',
      name: 'Sudha Paneer',
      brandId: IDS.brands.sudha,
      categoryId: IDS.categories.paneer,
      taxCodeId: IDS.taxCodes.dairyFive,
      isBatchTracked: true,
      isExpiryTracked: true,
      isReturnable: true,
      status: 'active',
    },
  ]
  for (const product of products) await upsertById(prisma.product, product)

  const variants = [
    { id: IDS.variants.tonedMilk500, organizationId: ORG_ID, productId: IDS.products.tonedMilk, sku: 'MILK-500', variantName: '500 ml', sizeValue: '0.500', unitId: IDS.units.litre, barcode: '890100000001', mrp: '28.00', distributorPrice: '25.50', defaultRetailerPrice: '26.50', offerPrice: '26.00', volumeLtr: '0.500', status: 'active' },
    { id: IDS.variants.tonedMilk1L, organizationId: ORG_ID, productId: IDS.products.tonedMilk, sku: 'MILK-1L', variantName: '1 Litre', sizeValue: '1.000', unitId: IDS.units.litre, barcode: '890100000002', mrp: '54.00', distributorPrice: '49.00', defaultRetailerPrice: '50.50', volumeLtr: '1.000', status: 'active' },
    { id: IDS.variants.dahi200, organizationId: ORG_ID, productId: IDS.products.dahi, sku: 'DAHI-200', variantName: '200 gm Cup', sizeValue: '200.000', unitId: IDS.units.gram, barcode: '890100000003', mrp: '25.00', distributorPrice: '20.50', defaultRetailerPrice: '22.00', status: 'active' },
    { id: IDS.variants.paneer1Kg, organizationId: ORG_ID, productId: IDS.products.paneer, sku: 'PANEER-1KG', variantName: '1 Kg Pack', sizeValue: '1.000', unitId: IDS.units.kg, barcode: '890100000004', mrp: '420.00', distributorPrice: '385.00', defaultRetailerPrice: '398.00', status: 'active' },
  ]
  for (const variant of variants) await upsertById(prisma.productVariant, variant)

  const images = [
    { id: IDS.images.tonedMilk500, organizationId: ORG_ID, variantId: IDS.variants.tonedMilk500, fileUrl: 'https://example.com/products/milk500.png', sortOrder: 1, isPrimary: true },
    { id: IDS.images.tonedMilk1L, organizationId: ORG_ID, variantId: IDS.variants.tonedMilk1L, fileUrl: 'https://example.com/products/milk1l.png', sortOrder: 1, isPrimary: true },
    { id: IDS.images.dahi200, organizationId: ORG_ID, variantId: IDS.variants.dahi200, fileUrl: 'https://example.com/products/dahi200.png', sortOrder: 1, isPrimary: true },
  ]
  for (const image of images) await upsertById(prisma.productImage, image)

  const priceBooks = [
    { id: IDS.priceBooks.defaultRetailer, organizationId: ORG_ID, code: 'PB-DEFAULT', name: 'Default Retailer Price Book', scopeType: 'default', priority: 10, validFrom: new Date('2026-01-01'), isActive: true },
    { id: IDS.priceBooks.patnaWholesale, organizationId: ORG_ID, code: 'PB-PATNA-WHOLESALE', name: 'Patna Wholesale Route Pricing', scopeType: 'route', priority: 5, validFrom: new Date('2026-01-01'), isActive: true },
  ]
  for (const priceBook of priceBooks) await upsertById(prisma.priceBook, priceBook)

  const assignments = [
    { id: IDS.priceBookAssignments.defaultCategory, organizationId: ORG_ID, priceBookId: IDS.priceBooks.defaultRetailer, retailerCategory: 'kirana', validFrom: new Date('2026-01-01') },
    { id: IDS.priceBookAssignments.patnaRouteWholesale, organizationId: ORG_ID, priceBookId: IDS.priceBooks.patnaWholesale, routeId: IDS.routes.patnaMorning, validFrom: new Date('2026-01-01') },
  ]
  for (const assignment of assignments) await upsertById(prisma.priceBookAssignment, assignment)

  const priceBookItems = [
    { id: IDS.priceBookItems.milk500Default, organizationId: ORG_ID, priceBookId: IDS.priceBooks.defaultRetailer, variantId: IDS.variants.tonedMilk500, basePrice: '26.50', offerPrice: '26.00', validFrom: new Date('2026-01-01T00:00:00+05:30') },
    { id: IDS.priceBookItems.milk1LDefault, organizationId: ORG_ID, priceBookId: IDS.priceBooks.defaultRetailer, variantId: IDS.variants.tonedMilk1L, basePrice: '50.50', validFrom: new Date('2026-01-01T00:00:00+05:30') },
    { id: IDS.priceBookItems.dahi200Default, organizationId: ORG_ID, priceBookId: IDS.priceBooks.defaultRetailer, variantId: IDS.variants.dahi200, basePrice: '22.00', validFrom: new Date('2026-01-01T00:00:00+05:30') },
    { id: IDS.priceBookItems.paneer1KgDefault, organizationId: ORG_ID, priceBookId: IDS.priceBooks.defaultRetailer, variantId: IDS.variants.paneer1Kg, basePrice: '398.00', validFrom: new Date('2026-01-01T00:00:00+05:30') },
  ]
  for (const item of priceBookItems) await upsertById(prisma.priceBookItem, item)

  await upsertById(prisma.promotion, {
    id: IDS.promotions.sawanOffer,
    organizationId: ORG_ID,
    code: 'SAWAN-2026',
    name: 'Sawan Retail Offer',
    promoType: 'festival',
    conditionsJson: { retailerCategories: ['kirana', 'booth'], minOrderValue: 500 },
    benefitsJson: { discountPercent: 2 },
    validFrom: new Date('2026-07-01T00:00:00+05:30'),
    validTo: new Date('2026-07-31T23:59:59+05:30'),
    isActive: true,
  })
}

async function seedWarehousingAndProcurementFlow() {
  const warehouses = [
    { id: IDS.warehouses.mainWarehouse, organizationId: ORG_ID, code: 'MAIN', name: 'Main Warehouse', warehouseType: 'main', addressJson: { city: 'Patna' }, isActive: true },
    { id: IDS.warehouses.returnsWarehouse, organizationId: ORG_ID, code: 'RET', name: 'Returns Warehouse', warehouseType: 'returns', addressJson: { city: 'Patna' }, isActive: true },
  ]
  for (const warehouse of warehouses) await upsertById(prisma.warehouse, warehouse)

  await upsertById(prisma.deliveryCycle, {
    id: IDS.deliveryCycles.morning_2026_07_10,
    organizationId: ORG_ID,
    cycleCode: 'DC-2026-07-10-MORNING',
    orderDate: new Date('2026-07-09'),
    deliveryDate: new Date('2026-07-10'),
    deliveryShift: 'morning',
    cutoffAt: SEED_DATES.cutoffAt,
    status: 'planned',
  })

  const salesOrders = [
    {
      id: IDS.salesOrders.anand,
      organizationId: ORG_ID,
      orderNo: 'SO-1001',
      retailerId: IDS.retailers.anandStore,
      routeId: IDS.routes.patnaMorning,
      deliveryCycleId: IDS.deliveryCycles.morning_2026_07_10,
      orderDate: SEED_DATES.orderDate,
      requestedDeliveryDate: SEED_DATES.deliveryDate,
      source: 'admin',
      orderingModeSnapshot: 'assisted',
      enteredByUserId: IDS.users.operations,
      enteredByEmployeeId: IDS.employees.operations,
      status: 'approved',
      subtotal: '569.00',
      discountTotal: '10.00',
      taxTotal: '0.00',
      grandTotal: '559.00',
      notes: 'Phone order entered by admin on behalf of retailer',
      approvedByUserId: IDS.users.operations,
      approvedAt: new Date('2026-07-09T19:00:00+05:30'),
    },
    {
      id: IDS.salesOrders.gupta,
      organizationId: ORG_ID,
      orderNo: 'SO-1002',
      retailerId: IDS.retailers.guptaSweets,
      routeId: IDS.routes.patnaMorning,
      deliveryCycleId: IDS.deliveryCycles.morning_2026_07_10,
      orderDate: SEED_DATES.orderDate,
      requestedDeliveryDate: SEED_DATES.deliveryDate,
      source: 'salesperson',
      orderingModeSnapshot: 'hybrid',
      enteredByUserId: IDS.users.sales1,
      enteredByEmployeeId: IDS.employees.sales1,
      status: 'approved',
      subtotal: '846.50',
      discountTotal: '0.00',
      taxTotal: '19.90',
      grandTotal: '866.40',
      notes: 'Salesperson assisted order',
      approvedByUserId: IDS.users.operations,
      approvedAt: new Date('2026-07-09T19:05:00+05:30'),
    },
    {
      id: IDS.salesOrders.freshMart,
      organizationId: ORG_ID,
      orderNo: 'SO-1003',
      retailerId: IDS.retailers.freshMart,
      routeId: IDS.routes.patnaMorning,
      deliveryCycleId: IDS.deliveryCycles.morning_2026_07_10,
      orderDate: SEED_DATES.orderDate,
      requestedDeliveryDate: SEED_DATES.deliveryDate,
      source: 'retailer',
      orderingModeSnapshot: 'self_service',
      enteredByUserId: IDS.users.retailerFreshMart,
      status: 'approved',
      subtotal: '530.00',
      discountTotal: '0.00',
      taxTotal: '0.00',
      grandTotal: '530.00',
      approvedByUserId: IDS.users.operations,
      approvedAt: new Date('2026-07-09T19:10:00+05:30'),
    },
  ]
  for (const order of salesOrders) await upsertById(prisma.salesOrder, order)

  const orderItems = [
    { id: IDS.salesOrderItems.anandMilk500, organizationId: ORG_ID, salesOrderId: IDS.salesOrders.anand, variantId: IDS.variants.tonedMilk500, orderedQty: '20.000', approvedQty: '20.000', unitPrice: '26.50', discountAmount: '10.00', taxRate: '0.00', taxAmount: '0.00', lineTotal: '520.00' },
    { id: IDS.salesOrderItems.anandDahi, organizationId: ORG_ID, salesOrderId: IDS.salesOrders.anand, variantId: IDS.variants.dahi200, orderedQty: '2.000', approvedQty: '2.000', unitPrice: '22.00', discountAmount: '0.00', taxRate: '0.00', taxAmount: '0.00', lineTotal: '44.00' },
    { id: IDS.salesOrderItems.guptaMilk1L, organizationId: ORG_ID, salesOrderId: IDS.salesOrders.gupta, variantId: IDS.variants.tonedMilk1L, orderedQty: '5.000', approvedQty: '5.000', unitPrice: '50.50', discountAmount: '0.00', taxRate: '0.00', taxAmount: '0.00', lineTotal: '252.50' },
    { id: IDS.salesOrderItems.guptaPaneer, organizationId: ORG_ID, salesOrderId: IDS.salesOrders.gupta, variantId: IDS.variants.paneer1Kg, orderedQty: '1.000', approvedQty: '1.000', unitPrice: '398.00', discountAmount: '0.00', taxRate: '5.00', taxAmount: '19.90', lineTotal: '417.90' },
    { id: IDS.salesOrderItems.freshMilk500, organizationId: ORG_ID, salesOrderId: IDS.salesOrders.freshMart, variantId: IDS.variants.tonedMilk500, orderedQty: '20.000', approvedQty: '20.000', unitPrice: '26.50', discountAmount: '0.00', taxRate: '0.00', taxAmount: '0.00', lineTotal: '530.00' },
  ]
  for (const item of orderItems) await upsertById(prisma.salesOrderItem, item)

  const statusRows = [
    { id: '00000000-0000-0000-0000-000000010201', organizationId: ORG_ID, salesOrderId: IDS.salesOrders.anand, oldStatus: 'pending', newStatus: 'approved', changedByUserId: IDS.users.operations, changedAt: new Date('2026-07-09T19:00:00+05:30'), note: 'Approved by operations' },
    { id: '00000000-0000-0000-0000-000000010202', organizationId: ORG_ID, salesOrderId: IDS.salesOrders.gupta, oldStatus: 'pending', newStatus: 'approved', changedByUserId: IDS.users.operations, changedAt: new Date('2026-07-09T19:05:00+05:30'), note: 'Approved by operations' },
    { id: '00000000-0000-0000-0000-000000010203', organizationId: ORG_ID, salesOrderId: IDS.salesOrders.freshMart, oldStatus: 'pending', newStatus: 'approved', changedByUserId: IDS.users.operations, changedAt: new Date('2026-07-09T19:10:00+05:30'), note: 'Approved by operations' },
  ]
  for (const row of statusRows) await upsertById(prisma.salesOrderStatusHistory, row)

  await upsertById(prisma.demandConsolidation, {
    id: IDS.demandConsolidations.dcMorning,
    organizationId: ORG_ID,
    consolidationNo: 'DCON-1001',
    deliveryCycleId: IDS.deliveryCycles.morning_2026_07_10,
    consolidationDate: new Date('2026-07-09'),
    status: 'approved',
    notes: 'Auto consolidated demand for next morning dispatch',
    createdByUserId: IDS.users.operations,
    approvedByUserId: IDS.users.owner,
    approvedAt: new Date('2026-07-09T21:10:00+05:30'),
  })

  const demandItems = [
    { id: IDS.demandItems.milk500, organizationId: ORG_ID, demandConsolidationId: IDS.demandConsolidations.dcMorning, variantId: IDS.variants.tonedMilk500, totalOrderQty: '40.000', totalApprovedQty: '40.000', bufferQty: '2.000', finalProcurementQty: '42.000' },
    { id: IDS.demandItems.milk1L, organizationId: ORG_ID, demandConsolidationId: IDS.demandConsolidations.dcMorning, variantId: IDS.variants.tonedMilk1L, totalOrderQty: '5.000', totalApprovedQty: '5.000', bufferQty: '1.000', finalProcurementQty: '6.000' },
    { id: IDS.demandItems.dahi200, organizationId: ORG_ID, demandConsolidationId: IDS.demandConsolidations.dcMorning, variantId: IDS.variants.dahi200, totalOrderQty: '2.000', totalApprovedQty: '2.000', bufferQty: '1.000', finalProcurementQty: '3.000' },
    { id: IDS.demandItems.paneer1Kg, organizationId: ORG_ID, demandConsolidationId: IDS.demandConsolidations.dcMorning, variantId: IDS.variants.paneer1Kg, totalOrderQty: '1.000', totalApprovedQty: '1.000', bufferQty: '0.000', finalProcurementQty: '1.000' },
  ]
  for (const item of demandItems) await upsertById(prisma.demandConsolidationItem, item)

  await prisma.demandSourceOrder.createMany({
    data: [
      { demandConsolidationId: IDS.demandConsolidations.dcMorning, salesOrderId: IDS.salesOrders.anand },
      { demandConsolidationId: IDS.demandConsolidations.dcMorning, salesOrderId: IDS.salesOrders.gupta },
      { demandConsolidationId: IDS.demandConsolidations.dcMorning, salesOrderId: IDS.salesOrders.freshMart },
    ],
    skipDuplicates: true,
  })

  await upsertById(prisma.purchaseOrder, {
    id: IDS.purchaseOrders.poMorning,
    organizationId: ORG_ID,
    poNo: 'PO-1001',
    supplierId: IDS.suppliers.sudhaDepot,
    demandConsolidationId: IDS.demandConsolidations.dcMorning,
    poDate: new Date('2026-07-09'),
    expectedReceiptDate: new Date('2026-07-10'),
    status: 'received',
    subtotal: '1536.50',
    taxTotal: '19.25',
    grandTotal: '1555.75',
    remarks: 'Generated automatically from daily demand consolidation',
    approvedByUserId: IDS.users.owner,
    approvedAt: new Date('2026-07-09T21:15:00+05:30'),
  })

  const poItems = [
    { id: IDS.purchaseOrderItems.milk500, organizationId: ORG_ID, purchaseOrderId: IDS.purchaseOrders.poMorning, variantId: IDS.variants.tonedMilk500, orderedQty: '42.000', unitCost: '25.50', taxRate: '0.00', taxAmount: '0.00', lineTotal: '1071.00' },
    { id: IDS.purchaseOrderItems.milk1L, organizationId: ORG_ID, purchaseOrderId: IDS.purchaseOrders.poMorning, variantId: IDS.variants.tonedMilk1L, orderedQty: '6.000', unitCost: '49.00', taxRate: '0.00', taxAmount: '0.00', lineTotal: '294.00' },
    { id: IDS.purchaseOrderItems.dahi200, organizationId: ORG_ID, purchaseOrderId: IDS.purchaseOrders.poMorning, variantId: IDS.variants.dahi200, orderedQty: '3.000', unitCost: '20.50', taxRate: '0.00', taxAmount: '0.00', lineTotal: '61.50' },
    { id: IDS.purchaseOrderItems.paneer1Kg, organizationId: ORG_ID, purchaseOrderId: IDS.purchaseOrders.poMorning, variantId: IDS.variants.paneer1Kg, orderedQty: '1.000', unitCost: '385.00', taxRate: '5.00', taxAmount: '19.25', lineTotal: '404.25' },
  ]
  for (const item of poItems) await upsertById(prisma.purchaseOrderItem, item)

  await upsertById(prisma.goodsReceipt, {
    id: IDS.goodsReceipts.grnMorning,
    organizationId: ORG_ID,
    grnNo: 'GRN-1001',
    supplierId: IDS.suppliers.sudhaDepot,
    purchaseOrderId: IDS.purchaseOrders.poMorning,
    warehouseId: IDS.warehouses.mainWarehouse,
    receiptDate: SEED_DATES.grnDate,
    supplierChallanNo: 'SD-CH-7788',
    vehicleNo: 'BR01CD4567',
    status: 'approved',
    remarks: 'Supplier quantity matched demand except dahi short supply',
    receivedByEmployeeId: IDS.employees.operations,
    approvedByUserId: IDS.users.operations,
    approvedAt: new Date('2026-07-10T05:00:00+05:30'),
  })

  const grnItems = [
    { id: IDS.goodsReceiptItems.milk500, organizationId: ORG_ID, goodsReceiptId: IDS.goodsReceipts.grnMorning, purchaseOrderItemId: IDS.purchaseOrderItems.milk500, variantId: IDS.variants.tonedMilk500, orderedQty: '42.000', receivedQty: '42.000', acceptedQty: '42.000', rejectedQty: '0.000', excessQty: '0.000', shortQty: '0.000', batchNo: 'MILK500-1007', manufacturingDate: new Date('2026-07-09'), expiryDate: new Date('2026-07-11'), unitCost: '25.50' },
    { id: IDS.goodsReceiptItems.milk1L, organizationId: ORG_ID, goodsReceiptId: IDS.goodsReceipts.grnMorning, purchaseOrderItemId: IDS.purchaseOrderItems.milk1L, variantId: IDS.variants.tonedMilk1L, orderedQty: '6.000', receivedQty: '6.000', acceptedQty: '6.000', rejectedQty: '0.000', excessQty: '0.000', shortQty: '0.000', batchNo: 'MILK1L-1007', manufacturingDate: new Date('2026-07-09'), expiryDate: new Date('2026-07-11'), unitCost: '49.00' },
    { id: IDS.goodsReceiptItems.dahi200, organizationId: ORG_ID, goodsReceiptId: IDS.goodsReceipts.grnMorning, purchaseOrderItemId: IDS.purchaseOrderItems.dahi200, variantId: IDS.variants.dahi200, orderedQty: '3.000', receivedQty: '2.000', acceptedQty: '2.000', rejectedQty: '0.000', excessQty: '0.000', shortQty: '1.000', batchNo: 'DAHI200-1007', manufacturingDate: new Date('2026-07-09'), expiryDate: new Date('2026-07-13'), unitCost: '20.50', remarks: 'Short supply by supplier' },
    { id: IDS.goodsReceiptItems.paneer1Kg, organizationId: ORG_ID, goodsReceiptId: IDS.goodsReceipts.grnMorning, purchaseOrderItemId: IDS.purchaseOrderItems.paneer1Kg, variantId: IDS.variants.paneer1Kg, orderedQty: '1.000', receivedQty: '1.000', acceptedQty: '1.000', rejectedQty: '0.000', excessQty: '0.000', shortQty: '0.000', batchNo: 'PANEER1KG-1007', manufacturingDate: new Date('2026-07-09'), expiryDate: new Date('2026-07-15'), unitCost: '385.00' },
  ]
  for (const item of grnItems) await upsertById(prisma.goodsReceiptItem, item)

  await upsertById(prisma.purchaseInvoice, {
    id: IDS.purchaseInvoices.supplierInvoice,
    organizationId: ORG_ID,
    invoiceNo: 'SUP-INV-9981',
    internalVoucherNo: 'PINV-1001',
    supplierId: IDS.suppliers.sudhaDepot,
    goodsReceiptId: IDS.goodsReceipts.grnMorning,
    invoiceDate: new Date('2026-07-10'),
    dueDate: new Date('2026-07-17'),
    taxableAmount: '1516.00',
    taxTotal: '19.25',
    grandTotal: '1535.25',
    status: 'posted',
    remarks: 'Supplier invoice after short supply adjustment',
    journalEntryId: IDS.journalEntries.purchase,
  })

  const purchaseInvoiceItems = [
    { id: IDS.purchaseInvoiceItems.milk500, organizationId: ORG_ID, purchaseInvoiceId: IDS.purchaseInvoices.supplierInvoice, goodsReceiptItemId: IDS.goodsReceiptItems.milk500, variantId: IDS.variants.tonedMilk500, billedQty: '42.000', unitCost: '25.50', taxRate: '0.00', taxAmount: '0.00', lineTotal: '1071.00' },
    { id: IDS.purchaseInvoiceItems.milk1L, organizationId: ORG_ID, purchaseInvoiceId: IDS.purchaseInvoices.supplierInvoice, goodsReceiptItemId: IDS.goodsReceiptItems.milk1L, variantId: IDS.variants.tonedMilk1L, billedQty: '6.000', unitCost: '49.00', taxRate: '0.00', taxAmount: '0.00', lineTotal: '294.00' },
    { id: IDS.purchaseInvoiceItems.dahi200, organizationId: ORG_ID, purchaseInvoiceId: IDS.purchaseInvoices.supplierInvoice, goodsReceiptItemId: IDS.goodsReceiptItems.dahi200, variantId: IDS.variants.dahi200, billedQty: '2.000', unitCost: '20.50', taxRate: '0.00', taxAmount: '0.00', lineTotal: '41.00' },
    { id: IDS.purchaseInvoiceItems.paneer1Kg, organizationId: ORG_ID, purchaseInvoiceId: IDS.purchaseInvoices.supplierInvoice, goodsReceiptItemId: IDS.goodsReceiptItems.paneer1Kg, variantId: IDS.variants.paneer1Kg, billedQty: '1.000', unitCost: '385.00', taxRate: '5.00', taxAmount: '19.25', lineTotal: '404.25' },
  ]
  for (const item of purchaseInvoiceItems) await upsertById(prisma.purchaseInvoiceItem, item)

  const batches = [
    { id: IDS.inventoryBatches.milk500, organizationId: ORG_ID, variantId: IDS.variants.tonedMilk500, warehouseId: IDS.warehouses.mainWarehouse, goodsReceiptItemId: IDS.goodsReceiptItems.milk500, batchNo: 'MILK500-1007', manufacturingDate: new Date('2026-07-09'), expiryDate: new Date('2026-07-11'), receivedQty: '42.000', availableQty: '42.000', reservedQty: '0.000', damagedQty: '0.000', status: 'active' },
    { id: IDS.inventoryBatches.milk1L, organizationId: ORG_ID, variantId: IDS.variants.tonedMilk1L, warehouseId: IDS.warehouses.mainWarehouse, goodsReceiptItemId: IDS.goodsReceiptItems.milk1L, batchNo: 'MILK1L-1007', manufacturingDate: new Date('2026-07-09'), expiryDate: new Date('2026-07-11'), receivedQty: '6.000', availableQty: '6.000', reservedQty: '0.000', damagedQty: '0.000', status: 'active' },
    { id: IDS.inventoryBatches.dahi200, organizationId: ORG_ID, variantId: IDS.variants.dahi200, warehouseId: IDS.warehouses.mainWarehouse, goodsReceiptItemId: IDS.goodsReceiptItems.dahi200, batchNo: 'DAHI200-1007', manufacturingDate: new Date('2026-07-09'), expiryDate: new Date('2026-07-13'), receivedQty: '2.000', availableQty: '2.000', reservedQty: '0.000', damagedQty: '0.000', status: 'active' },
    { id: IDS.inventoryBatches.paneer1Kg, organizationId: ORG_ID, variantId: IDS.variants.paneer1Kg, warehouseId: IDS.warehouses.mainWarehouse, goodsReceiptItemId: IDS.goodsReceiptItems.paneer1Kg, batchNo: 'PANEER1KG-1007', manufacturingDate: new Date('2026-07-09'), expiryDate: new Date('2026-07-15'), receivedQty: '1.000', availableQty: '1.000', reservedQty: '0.000', damagedQty: '0.000', status: 'active' },
  ]
  for (const batch of batches) await upsertById(prisma.inventoryBatch, batch)

  const stockMovements = [
    { id: IDS.stockMovements.grnMilk500, organizationId: ORG_ID, movementNo: 'SM-1001', warehouseId: IDS.warehouses.mainWarehouse, variantId: IDS.variants.tonedMilk500, inventoryBatchId: IDS.inventoryBatches.milk500, movementType: 'grn_in', referenceType: 'grn', referenceId: IDS.goodsReceipts.grnMorning, qtyIn: '42.000', qtyOut: '0.000', unitCost: '25.50', movementAt: SEED_DATES.grnDate },
    { id: IDS.stockMovements.grnMilk1L, organizationId: ORG_ID, movementNo: 'SM-1002', warehouseId: IDS.warehouses.mainWarehouse, variantId: IDS.variants.tonedMilk1L, inventoryBatchId: IDS.inventoryBatches.milk1L, movementType: 'grn_in', referenceType: 'grn', referenceId: IDS.goodsReceipts.grnMorning, qtyIn: '6.000', qtyOut: '0.000', unitCost: '49.00', movementAt: SEED_DATES.grnDate },
    { id: IDS.stockMovements.grnDahi200, organizationId: ORG_ID, movementNo: 'SM-1003', warehouseId: IDS.warehouses.mainWarehouse, variantId: IDS.variants.dahi200, inventoryBatchId: IDS.inventoryBatches.dahi200, movementType: 'grn_in', referenceType: 'grn', referenceId: IDS.goodsReceipts.grnMorning, qtyIn: '2.000', qtyOut: '0.000', unitCost: '20.50', movementAt: SEED_DATES.grnDate },
    { id: IDS.stockMovements.grnPaneer1Kg, organizationId: ORG_ID, movementNo: 'SM-1004', warehouseId: IDS.warehouses.mainWarehouse, variantId: IDS.variants.paneer1Kg, inventoryBatchId: IDS.inventoryBatches.paneer1Kg, movementType: 'grn_in', referenceType: 'grn', referenceId: IDS.goodsReceipts.grnMorning, qtyIn: '1.000', qtyOut: '0.000', unitCost: '385.00', movementAt: SEED_DATES.grnDate },
  ]
  for (const movement of stockMovements) await upsertById(prisma.stockMovement, movement)
}

async function seedDispatchAndSalesFlow() {
  await upsertById(prisma.dispatchTrip, {
    id: IDS.dispatchTrips.morningTrip,
    organizationId: ORG_ID,
    tripNo: 'TRIP-1001',
    deliveryCycleId: IDS.deliveryCycles.morning_2026_07_10,
    routeId: IDS.routes.patnaMorning,
    vehicleId: IDS.vehicles.van1,
    driverEmployeeId: IDS.employees.driver1,
    helperEmployeeId: IDS.employees.sales1,
    dispatchDate: SEED_DATES.dispatchDate,
    plannedStartAt: new Date('2026-07-10T05:30:00+05:30'),
    actualStartAt: new Date('2026-07-10T05:40:00+05:30'),
    actualEndAt: new Date('2026-07-10T09:15:00+05:30'),
    status: 'reconciled',
    loadingSheetNo: 'LOAD-1001',
    challanNo: 'CHL-1001',
    totalStops: 3,
    totalCratesLoaded: 4,
    notes: 'Morning city route completed',
  })

  const tripItems = [
    { id: IDS.dispatchTripItems.milk500, organizationId: ORG_ID, dispatchTripId: IDS.dispatchTrips.morningTrip, variantId: IDS.variants.tonedMilk500, plannedQty: '40.000', loadedQty: '40.000', sourceWarehouseId: IDS.warehouses.mainWarehouse, inventoryBatchId: IDS.inventoryBatches.milk500 },
    { id: IDS.dispatchTripItems.milk1L, organizationId: ORG_ID, dispatchTripId: IDS.dispatchTrips.morningTrip, variantId: IDS.variants.tonedMilk1L, plannedQty: '5.000', loadedQty: '5.000', sourceWarehouseId: IDS.warehouses.mainWarehouse, inventoryBatchId: IDS.inventoryBatches.milk1L },
    { id: IDS.dispatchTripItems.dahi200, organizationId: ORG_ID, dispatchTripId: IDS.dispatchTrips.morningTrip, variantId: IDS.variants.dahi200, plannedQty: '2.000', loadedQty: '2.000', sourceWarehouseId: IDS.warehouses.mainWarehouse, inventoryBatchId: IDS.inventoryBatches.dahi200 },
    { id: IDS.dispatchTripItems.paneer1Kg, organizationId: ORG_ID, dispatchTripId: IDS.dispatchTrips.morningTrip, variantId: IDS.variants.paneer1Kg, plannedQty: '1.000', loadedQty: '1.000', sourceWarehouseId: IDS.warehouses.mainWarehouse, inventoryBatchId: IDS.inventoryBatches.paneer1Kg },
  ]
  for (const item of tripItems) await upsertById(prisma.dispatchTripItem, item)

  await upsertById(prisma.deliveryChallan, {
    id: IDS.deliveryChallans.morningTrip,
    organizationId: ORG_ID,
    challanNo: 'CHL-1001',
    dispatchTripId: IDS.dispatchTrips.morningTrip,
    issueDate: SEED_DATES.dispatchDate,
    status: 'closed',
    pdfUrl: 'https://example.com/challan/chl-1001.pdf',
  })

  const stops = [
    { id: IDS.deliveryStops.anand, organizationId: ORG_ID, dispatchTripId: IDS.dispatchTrips.morningTrip, retailerId: IDS.retailers.anandStore, salesOrderId: IDS.salesOrders.anand, stopSequence: 1, plannedArrivalAt: new Date('2026-07-10T06:00:00+05:30'), actualArrivalAt: new Date('2026-07-10T06:10:00+05:30'), actualDepartureAt: new Date('2026-07-10T06:25:00+05:30'), status: 'delivered', cratesIssued: 2, emptyCratesReceived: 1, notes: 'Delivered against admin-created order' },
    { id: IDS.deliveryStops.gupta, organizationId: ORG_ID, dispatchTripId: IDS.dispatchTrips.morningTrip, retailerId: IDS.retailers.guptaSweets, salesOrderId: IDS.salesOrders.gupta, stopSequence: 2, plannedArrivalAt: new Date('2026-07-10T06:40:00+05:30'), actualArrivalAt: new Date('2026-07-10T06:55:00+05:30'), actualDepartureAt: new Date('2026-07-10T07:20:00+05:30'), status: 'delivered', cratesIssued: 1, emptyCratesReceived: 0 },
    { id: IDS.deliveryStops.freshMart, organizationId: ORG_ID, dispatchTripId: IDS.dispatchTrips.morningTrip, retailerId: IDS.retailers.freshMart, salesOrderId: IDS.salesOrders.freshMart, stopSequence: 3, plannedArrivalAt: new Date('2026-07-10T07:30:00+05:30'), actualArrivalAt: new Date('2026-07-10T07:45:00+05:30'), actualDepartureAt: new Date('2026-07-10T08:05:00+05:30'), status: 'delivered', cratesIssued: 1, emptyCratesReceived: 1 },
  ]
  for (const stop of stops) await upsertById(prisma.deliveryStop, stop)

  const stopItems = [
    { id: IDS.deliveryStopItems.anandMilk500, organizationId: ORG_ID, deliveryStopId: IDS.deliveryStops.anand, salesOrderItemId: IDS.salesOrderItems.anandMilk500, variantId: IDS.variants.tonedMilk500, orderedQty: '20.000', loadedQty: '20.000', deliveredQty: '20.000', returnedQty: '0.000', damagedQty: '0.000', refusedQty: '0.000', unitPrice: '26.50', taxAmount: '0.00', lineTotal: '520.00' },
    { id: IDS.deliveryStopItems.anandDahi, organizationId: ORG_ID, deliveryStopId: IDS.deliveryStops.anand, salesOrderItemId: IDS.salesOrderItems.anandDahi, variantId: IDS.variants.dahi200, orderedQty: '2.000', loadedQty: '2.000', deliveredQty: '2.000', returnedQty: '0.000', damagedQty: '0.000', refusedQty: '0.000', unitPrice: '22.00', taxAmount: '0.00', lineTotal: '44.00' },
    { id: IDS.deliveryStopItems.guptaMilk1L, organizationId: ORG_ID, deliveryStopId: IDS.deliveryStops.gupta, salesOrderItemId: IDS.salesOrderItems.guptaMilk1L, variantId: IDS.variants.tonedMilk1L, orderedQty: '5.000', loadedQty: '5.000', deliveredQty: '5.000', returnedQty: '0.000', damagedQty: '0.000', refusedQty: '0.000', unitPrice: '50.50', taxAmount: '0.00', lineTotal: '252.50' },
    { id: IDS.deliveryStopItems.guptaPaneer, organizationId: ORG_ID, deliveryStopId: IDS.deliveryStops.gupta, salesOrderItemId: IDS.salesOrderItems.guptaPaneer, variantId: IDS.variants.paneer1Kg, orderedQty: '1.000', loadedQty: '1.000', deliveredQty: '1.000', returnedQty: '0.000', damagedQty: '0.000', refusedQty: '0.000', unitPrice: '398.00', taxAmount: '19.90', lineTotal: '417.90' },
    { id: IDS.deliveryStopItems.freshMilk500, organizationId: ORG_ID, deliveryStopId: IDS.deliveryStops.freshMart, salesOrderItemId: IDS.salesOrderItems.freshMilk500, variantId: IDS.variants.tonedMilk500, orderedQty: '20.000', loadedQty: '20.000', deliveredQty: '20.000', returnedQty: '0.000', damagedQty: '0.000', refusedQty: '0.000', unitPrice: '26.50', taxAmount: '0.00', lineTotal: '530.00' },
  ]
  for (const item of stopItems) await upsertById(prisma.deliveryStopItem, item)

  await upsertById(prisma.tripReconciliation, {
    id: IDS.tripReconciliations.morningTrip,
    organizationId: ORG_ID,
    dispatchTripId: IDS.dispatchTrips.morningTrip,
    reconciledByUserId: IDS.users.operations,
    loadedQtyTotal: '48.000',
    deliveredQtyTotal: '48.000',
    returnedQtyTotal: '0.000',
    damagedQtyTotal: '0.000',
    missingQtyTotal: '0.000',
    cashCollectedTotal: '800.00',
    cratesVariance: 1,
    closedAt: new Date('2026-07-10T10:00:00+05:30'),
    notes: 'One crate pending with retailer Anand Store',
  })

  const invoices = [
    {
      id: IDS.salesInvoices.anand,
      organizationId: ORG_ID,
      invoiceNo: 'INV-1001',
      retailerId: IDS.retailers.anandStore,
      salesOrderId: IDS.salesOrders.anand,
      dispatchTripId: IDS.dispatchTrips.morningTrip,
      invoiceDate: SEED_DATES.invoiceDate,
      dueDate: new Date('2026-07-15'),
      source: 'assisted_billing',
      createdByUserId: IDS.users.operations,
      status: 'partial_paid',
      subtotal: '564.00',
      discountTotal: '5.00',
      taxTotal: '0.00',
      grandTotal: '559.00',
      outstandingAmount: '159.00',
      pdfUrl: 'https://example.com/invoices/inv-1001.pdf',
      remarks: 'Invoice generated by admin on behalf of retailer',
      journalEntryId: IDS.journalEntries.saleAnand,
    },
    {
      id: IDS.salesInvoices.gupta,
      organizationId: ORG_ID,
      invoiceNo: 'INV-1002',
      retailerId: IDS.retailers.guptaSweets,
      salesOrderId: IDS.salesOrders.gupta,
      dispatchTripId: IDS.dispatchTrips.morningTrip,
      invoiceDate: SEED_DATES.invoiceDate,
      dueDate: new Date('2026-07-17'),
      source: 'auto_delivery',
      createdByUserId: IDS.users.operations,
      status: 'partial_paid',
      subtotal: '650.50',
      discountTotal: '0.00',
      taxTotal: '19.90',
      grandTotal: '670.40',
      outstandingAmount: '29.40',
      pdfUrl: 'https://example.com/invoices/inv-1002.pdf',
      journalEntryId: IDS.journalEntries.saleGupta,
    },
    {
      id: IDS.salesInvoices.freshMart,
      organizationId: ORG_ID,
      invoiceNo: 'INV-1003',
      retailerId: IDS.retailers.freshMart,
      salesOrderId: IDS.salesOrders.freshMart,
      dispatchTripId: IDS.dispatchTrips.morningTrip,
      invoiceDate: SEED_DATES.invoiceDate,
      dueDate: new Date('2026-07-13'),
      source: 'auto_delivery',
      createdByUserId: IDS.users.operations,
      status: 'posted',
      subtotal: '530.00',
      discountTotal: '0.00',
      taxTotal: '0.00',
      grandTotal: '530.00',
      outstandingAmount: '530.00',
      pdfUrl: 'https://example.com/invoices/inv-1003.pdf',
    },
  ]
  for (const invoice of invoices) await upsertById(prisma.salesInvoice, invoice)

  const invoiceItems = [
    { id: IDS.salesInvoiceItems.anandMilk500, organizationId: ORG_ID, salesInvoiceId: IDS.salesInvoices.anand, deliveryStopItemId: IDS.deliveryStopItems.anandMilk500, variantId: IDS.variants.tonedMilk500, billedQty: '20.000', unitPrice: '26.50', discountAmount: '5.00', taxRate: '0.00', taxAmount: '0.00', lineTotal: '525.00' },
    { id: IDS.salesInvoiceItems.anandDahi, organizationId: ORG_ID, salesInvoiceId: IDS.salesInvoices.anand, deliveryStopItemId: IDS.deliveryStopItems.anandDahi, variantId: IDS.variants.dahi200, billedQty: '2.000', unitPrice: '22.00', discountAmount: '0.00', taxRate: '0.00', taxAmount: '0.00', lineTotal: '44.00' },
    { id: IDS.salesInvoiceItems.guptaMilk1L, organizationId: ORG_ID, salesInvoiceId: IDS.salesInvoices.gupta, deliveryStopItemId: IDS.deliveryStopItems.guptaMilk1L, variantId: IDS.variants.tonedMilk1L, billedQty: '5.000', unitPrice: '50.50', discountAmount: '0.00', taxRate: '0.00', taxAmount: '0.00', lineTotal: '252.50' },
    { id: IDS.salesInvoiceItems.guptaPaneer, organizationId: ORG_ID, salesInvoiceId: IDS.salesInvoices.gupta, deliveryStopItemId: IDS.deliveryStopItems.guptaPaneer, variantId: IDS.variants.paneer1Kg, billedQty: '1.000', unitPrice: '398.00', discountAmount: '0.00', taxRate: '5.00', taxAmount: '19.90', lineTotal: '417.90' },
    { id: IDS.salesInvoiceItems.freshMilk500, organizationId: ORG_ID, salesInvoiceId: IDS.salesInvoices.freshMart, deliveryStopItemId: IDS.deliveryStopItems.freshMilk500, variantId: IDS.variants.tonedMilk500, billedQty: '20.000', unitPrice: '26.50', discountAmount: '0.00', taxRate: '0.00', taxAmount: '0.00', lineTotal: '530.00' },
  ]
  for (const item of invoiceItems) await upsertById(prisma.salesInvoiceItem, item)

  const receipts = [
    { id: IDS.paymentReceipts.anand, organizationId: ORG_ID, receiptNo: 'RCPT-1001', partyType: 'retailer', partyId: IDS.retailers.anandStore, paymentDirection: 'inbound', paymentMode: 'cash', paymentDate: SEED_DATES.paymentDate, amount: '400.00', collectedByUserId: IDS.users.driver1, collectedByEmployeeId: IDS.employees.driver1, dispatchTripId: IDS.dispatchTrips.morningTrip, cashRegisterId: IDS.cashRegisters.mainCash, status: 'confirmed', remarks: 'Part collection at delivery', journalEntryId: IDS.journalEntries.receiptAnand },
    { id: IDS.paymentReceipts.gupta, organizationId: ORG_ID, receiptNo: 'RCPT-1002', partyType: 'retailer', partyId: IDS.retailers.guptaSweets, paymentDirection: 'inbound', paymentMode: 'upi', paymentDate: new Date('2026-07-10T11:30:00+05:30'), amount: '641.00', collectedByUserId: IDS.users.driver1, collectedByEmployeeId: IDS.employees.driver1, dispatchTripId: IDS.dispatchTrips.morningTrip, bankAccountId: IDS.bankAccounts.mainBank, referenceNo: 'UPI-REF-23456', status: 'confirmed', journalEntryId: IDS.journalEntries.receiptGupta },
  ]
  for (const receipt of receipts) await upsertById(prisma.paymentReceipt, receipt)

  const allocations = [
    { id: IDS.paymentAllocations.anand, organizationId: ORG_ID, paymentReceiptId: IDS.paymentReceipts.anand, salesInvoiceId: IDS.salesInvoices.anand, allocatedAmount: '400.00', allocationDate: new Date('2026-07-10') },
    { id: IDS.paymentAllocations.gupta, organizationId: ORG_ID, paymentReceiptId: IDS.paymentReceipts.gupta, salesInvoiceId: IDS.salesInvoices.gupta, allocatedAmount: '641.00', allocationDate: new Date('2026-07-10') },
  ]
  for (const allocation of allocations) await upsertById(prisma.paymentAllocation, allocation)

  const crateTransactions = [
    { id: IDS.crateTransactions.anandIssue, organizationId: ORG_ID, crateTypeId: IDS.crateTypes.milkCrate, retailerId: IDS.retailers.anandStore, dispatchTripId: IDS.dispatchTrips.morningTrip, deliveryStopId: IDS.deliveryStops.anand, transactionType: 'issue', quantity: 2, transactionDate: new Date('2026-07-10T06:15:00+05:30'), referenceType: 'stop', referenceId: IDS.deliveryStops.anand, remarks: 'Milk crates issued' },
    { id: IDS.crateTransactions.anandReturn, organizationId: ORG_ID, crateTypeId: IDS.crateTypes.milkCrate, retailerId: IDS.retailers.anandStore, dispatchTripId: IDS.dispatchTrips.morningTrip, deliveryStopId: IDS.deliveryStops.anand, transactionType: 'return', quantity: 1, transactionDate: new Date('2026-07-10T06:16:00+05:30'), referenceType: 'stop', referenceId: IDS.deliveryStops.anand, remarks: 'One empty crate returned' },
    { id: IDS.crateTransactions.guptaIssue, organizationId: ORG_ID, crateTypeId: IDS.crateTypes.milkCrate, retailerId: IDS.retailers.guptaSweets, dispatchTripId: IDS.dispatchTrips.morningTrip, deliveryStopId: IDS.deliveryStops.gupta, transactionType: 'issue', quantity: 1, transactionDate: new Date('2026-07-10T07:00:00+05:30'), referenceType: 'stop', referenceId: IDS.deliveryStops.gupta },
  ]
  for (const transaction of crateTransactions) await upsertById(prisma.crateTransaction, transaction)

  const snapshots = [
    { id: IDS.crateBalanceSnapshots.anand, organizationId: ORG_ID, balanceDate: new Date('2026-07-10'), retailerId: IDS.retailers.anandStore, crateTypeId: IDS.crateTypes.milkCrate, openingQty: 0, issuedQty: 2, returnedQty: 1, damagedQty: 0, missingQty: 0, closingQty: 1 },
    { id: IDS.crateBalanceSnapshots.gupta, organizationId: ORG_ID, balanceDate: new Date('2026-07-10'), retailerId: IDS.retailers.guptaSweets, crateTypeId: IDS.crateTypes.milkCrate, openingQty: 0, issuedQty: 1, returnedQty: 0, damagedQty: 0, missingQty: 0, closingQty: 1 },
  ]
  for (const snapshot of snapshots) await upsertById(prisma.crateBalanceSnapshot, snapshot)
}

async function seedFinanceDemo() {
  const journalEntries = [
    { id: IDS.journalEntries.purchase, organizationId: ORG_ID, voucherNo: 'JV-PUR-1001', voucherType: 'purchase', entryDate: new Date('2026-07-10'), postingDate: new Date('2026-07-10'), referenceType: 'purchase_invoice', referenceId: IDS.purchaseInvoices.supplierInvoice, narration: 'Purchase invoice booking from Sudha Depot', status: 'posted', postedByUserId: IDS.users.accountant },
    { id: IDS.journalEntries.saleAnand, organizationId: ORG_ID, voucherNo: 'JV-SAL-1001', voucherType: 'sales', entryDate: new Date('2026-07-10'), postingDate: new Date('2026-07-10'), referenceType: 'sales_invoice', referenceId: IDS.salesInvoices.anand, narration: 'Sale invoice for Anand Store', status: 'posted', postedByUserId: IDS.users.accountant },
    { id: IDS.journalEntries.saleGupta, organizationId: ORG_ID, voucherNo: 'JV-SAL-1002', voucherType: 'sales', entryDate: new Date('2026-07-10'), postingDate: new Date('2026-07-10'), referenceType: 'sales_invoice', referenceId: IDS.salesInvoices.gupta, narration: 'Sale invoice for Gupta Sweets', status: 'posted', postedByUserId: IDS.users.accountant },
    { id: IDS.journalEntries.receiptAnand, organizationId: ORG_ID, voucherNo: 'JV-RCT-1001', voucherType: 'receipt', entryDate: new Date('2026-07-10'), postingDate: new Date('2026-07-10'), referenceType: 'payment_receipt', referenceId: IDS.paymentReceipts.anand, narration: 'Cash receipt from Anand Store', status: 'posted', postedByUserId: IDS.users.accountant },
    { id: IDS.journalEntries.receiptGupta, organizationId: ORG_ID, voucherNo: 'JV-RCT-1002', voucherType: 'receipt', entryDate: new Date('2026-07-10'), postingDate: new Date('2026-07-10'), referenceType: 'payment_receipt', referenceId: IDS.paymentReceipts.gupta, narration: 'UPI receipt from Gupta Sweets', status: 'posted', postedByUserId: IDS.users.accountant },
  ]
  for (const entry of journalEntries) await upsertById(prisma.journalEntry, entry)

  const journalLines = [
    { id: IDS.journalLines.purchaseInventoryDr, organizationId: ORG_ID, journalEntryId: IDS.journalEntries.purchase, accountId: IDS.accounts.inventory, debitAmount: '1535.25', creditAmount: '0.00', lineNarration: 'Inventory received from supplier' },
    { id: IDS.journalLines.purchaseSupplierCr, organizationId: ORG_ID, journalEntryId: IDS.journalEntries.purchase, accountId: IDS.accounts.payables, supplierId: IDS.suppliers.sudhaDepot, debitAmount: '0.00', creditAmount: '1535.25', lineNarration: 'Payable to supplier' },
    { id: IDS.journalLines.saleAnandReceivableDr, organizationId: ORG_ID, journalEntryId: IDS.journalEntries.saleAnand, accountId: IDS.accounts.receivables, retailerId: IDS.retailers.anandStore, debitAmount: '559.00', creditAmount: '0.00', lineNarration: 'Receivable from Anand Store' },
    { id: IDS.journalLines.saleAnandSalesCr, organizationId: ORG_ID, journalEntryId: IDS.journalEntries.saleAnand, accountId: IDS.accounts.sales, debitAmount: '0.00', creditAmount: '559.00', lineNarration: 'Sales booking Anand Store' },
    { id: IDS.journalLines.saleGuptaReceivableDr, organizationId: ORG_ID, journalEntryId: IDS.journalEntries.saleGupta, accountId: IDS.accounts.receivables, retailerId: IDS.retailers.guptaSweets, debitAmount: '670.40', creditAmount: '0.00', lineNarration: 'Receivable from Gupta Sweets' },
    { id: IDS.journalLines.saleGuptaSalesCr, organizationId: ORG_ID, journalEntryId: IDS.journalEntries.saleGupta, accountId: IDS.accounts.sales, debitAmount: '0.00', creditAmount: '670.40', lineNarration: 'Sales booking Gupta Sweets' },
    { id: IDS.journalLines.receiptAnandCashDr, organizationId: ORG_ID, journalEntryId: IDS.journalEntries.receiptAnand, accountId: IDS.accounts.cash, debitAmount: '400.00', creditAmount: '0.00', lineNarration: 'Cash received' },
    { id: IDS.journalLines.receiptAnandReceivableCr, organizationId: ORG_ID, journalEntryId: IDS.journalEntries.receiptAnand, accountId: IDS.accounts.receivables, retailerId: IDS.retailers.anandStore, debitAmount: '0.00', creditAmount: '400.00', lineNarration: 'Receivable adjusted' },
    { id: IDS.journalLines.receiptGuptaCashDr, organizationId: ORG_ID, journalEntryId: IDS.journalEntries.receiptGupta, accountId: IDS.accounts.bank, debitAmount: '641.00', creditAmount: '0.00', lineNarration: 'UPI/bank receipt' },
    { id: IDS.journalLines.receiptGuptaReceivableCr, organizationId: ORG_ID, journalEntryId: IDS.journalEntries.receiptGupta, accountId: IDS.accounts.receivables, retailerId: IDS.retailers.guptaSweets, debitAmount: '0.00', creditAmount: '641.00', lineNarration: 'Receivable adjusted' },
  ]
  for (const line of journalLines) await upsertById(prisma.accountJournalLine, line)

  await upsertById(prisma.expenseEntry, {
    id: IDS.expenseEntries.fuel,
    organizationId: ORG_ID,
    voucherNo: 'EXP-1001',
    expenseDate: new Date('2026-07-10'),
    expenseCategoryId: IDS.expenseCategories.fuel,
    amount: '850.00',
    taxAmount: '0.00',
    paymentMode: 'cash',
    paidFromAccountId: IDS.accounts.cash,
    description: 'Fuel expense for morning delivery vehicle',
  })

  await upsertById(prisma.dayClosing, {
    id: IDS.dayClosings.sample,
    organizationId: ORG_ID,
    closingDate: SEED_DATES.closingDate,
    cashRegisterId: IDS.cashRegisters.mainCash,
    openedByUserId: IDS.users.accountant,
    closedByUserId: IDS.users.accountant,
    openingBalance: '5000.00',
    cashReceived: '400.00',
    cashPaid: '850.00',
    expectedClosing: '4550.00',
    actualClosing: '4550.00',
    varianceAmount: '0.00',
    notes: 'Sample day closing for demo environment',
  })
}

async function seedNotificationsAndExtensions() {
  const templates = [
    { id: IDS.notificationTemplates.orderConfirmedWhatsApp, organizationId: ORG_ID, channel: 'whatsapp', eventKey: 'order_confirmed', languageCode: 'en', templateText: 'Your order {{orderNo}} has been confirmed for {{deliveryDate}}.', isActive: true },
    { id: IDS.notificationTemplates.paymentReceivedSms, organizationId: ORG_ID, channel: 'sms', eventKey: 'payment_received', languageCode: 'en', templateText: 'Payment of ₹{{amount}} received. Thank you.', isActive: true },
  ]
  for (const template of templates) await upsertById(prisma.notificationTemplate, template)

  await upsertById(prisma.notificationLog, {
    id: IDS.notificationLogs.anandOrderConfirmed,
    organizationId: ORG_ID,
    templateId: IDS.notificationTemplates.orderConfirmedWhatsApp,
    channel: 'whatsapp',
    eventKey: 'order_confirmed',
    recipientUserId: IDS.users.retailerAnand,
    recipientMobile: '9345678901',
    referenceType: 'order',
    referenceId: IDS.salesOrders.anand,
    payloadJson: { orderNo: 'SO-1001', deliveryDate: '2026-07-10' },
    status: 'sent',
    sentAt: new Date('2026-07-09T19:01:00+05:30'),
  })

  await upsertById(prisma.fileAttachment, {
    id: '00000000-0000-0000-0000-000000010301',
    organizationId: ORG_ID,
    entityType: 'sales_invoice',
    entityId: IDS.salesInvoices.anand,
    fileName: 'inv-1001.pdf',
    fileUrl: 'https://example.com/invoices/inv-1001.pdf',
    mimeType: 'application/pdf',
    metaJson: { generatedBy: 'seed' },
  })

  await upsertById(prisma.syncEvent, {
    id: IDS.syncEvents.deliveryUpdate,
    organizationId: ORG_ID,
    userId: IDS.users.driver1,
    deviceId: 'device-driver-01',
    entityType: 'delivery_stop',
    entityId: IDS.deliveryStops.anand,
    action: 'update',
    payloadJson: { status: 'delivered', collectedAmount: 400 },
    clientTimestamp: new Date('2026-07-10T06:20:00+05:30'),
    serverTimestamp: new Date('2026-07-10T06:20:10+05:30'),
    syncStatus: 'applied',
    conflictNotes: null,
  })

  await upsertById(prisma.forecastRun, {
    id: IDS.forecastRuns.demand,
    organizationId: ORG_ID,
    forecastType: 'demand',
    runDate: new Date('2026-07-09'),
    modelVersion: 'v1-demo',
    inputPeriodFrom: new Date('2026-06-01'),
    inputPeriodTo: new Date('2026-07-08'),
    status: 'completed',
    outputJson: { summary: 'Milk 500ml expected high demand tomorrow' },
  })

  const forecastItems = [
    { id: IDS.forecastItems.milk500, organizationId: ORG_ID, forecastRunId: IDS.forecastRuns.demand, variantId: IDS.variants.tonedMilk500, routeId: IDS.routes.patnaMorning, predictedQty: '45.000', confidenceScore: '91.20', recommendedPurchaseQty: '47.000' },
    { id: IDS.forecastItems.milk1L, organizationId: ORG_ID, forecastRunId: IDS.forecastRuns.demand, variantId: IDS.variants.tonedMilk1L, routeId: IDS.routes.patnaMorning, predictedQty: '6.000', confidenceScore: '82.40', recommendedPurchaseQty: '7.000' },
  ]
  for (const item of forecastItems) await upsertById(prisma.forecastItem, item)
}

async function main() {
  console.log('Seeding Dairy Distributor ERP structure...')

  await seedCoreOrganization()
  await seedAccountingMasters()
  await seedOperationsMasters()
  await seedUsers()
  await seedCatalog()
  await seedWarehousingAndProcurementFlow()
  await seedDispatchAndSalesFlow()
  await seedFinanceDemo()
  await seedNotificationsAndExtensions()

  console.log('Seed completed successfully.')
}

main()
  .catch((error) => {
    console.error('Seed failed:', error)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
