'use client';

import { EmptyState } from '@/components/feedback/empty-state';
import { PageHeader } from '@/components/ui/page-header';
import { PortalApi } from '@/features/portal/api';
import { formatCurrency } from '@/lib/utils/number';
import { useQuery } from '@tanstack/react-query';
import Link from 'next/link';
import { useMemo, useState } from 'react';

export function PortalInvoicesView() {
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [exportMessage, setExportMessage] = useState<string | null>(null);

  const queryKey = useMemo(() => ['portal', 'invoices', search, status], [search, status]);
  const query = useQuery({
    queryKey,
    queryFn: () =>
      PortalApi.getInvoices({
        page: 1,
        limit: 20,
        search: search || undefined,
        status: status || undefined,
      }),
  });

  const rows = query.data?.data ?? [];
  const meta = query.data?.meta;

  const handleExport = async (id: string, invoiceNo: string, format: 'pdf' | 'print') => {
    try {
      setExportMessage(`Generating ${format.toUpperCase()} for invoice ${invoiceNo}...`);
      const response = await PortalApi.exportInvoice(id, format);
      if (response.success && response.data) {
        setExportMessage(`Invoice ${invoiceNo} exported successfully (${response.data.fileName}).`);
      }
    } catch (error) {
      setExportMessage(error instanceof Error ? error.message : `Failed to export invoice ${invoiceNo}`);
    }
  };

  const getSourceBadge = (source: string) => {
    if (source === 'assisted_billing') {
      return { label: 'Assisted Billing', className: 'bg-purple-100 text-purple-800 border-purple-200' };
    }
    if (source === 'auto') {
      return { label: 'Delivery Billing', className: 'bg-emerald-100 text-emerald-800 border-emerald-200' };
    }
    return { label: source.replace(/_/g, ' ').toUpperCase(), className: 'bg-slate-100 text-slate-800 border-slate-200' };
  };

  const getStatusBadge = (statusStr: string, outstanding: number) => {
    if (statusStr === 'paid' || outstanding <= 0) {
      return { label: 'Paid', className: 'bg-emerald-100 text-emerald-800 border-emerald-200' };
    }
    if (statusStr === 'partial_paid' || (outstanding > 0 && outstanding < 1000000 && statusStr === 'posted')) {
      return { label: 'Partial / Unpaid', className: 'bg-amber-100 text-amber-800 border-amber-200' };
    }
    if (statusStr === 'revised') {
      return { label: 'Revised', className: 'bg-blue-100 text-blue-800 border-blue-200' };
    }
    if (statusStr === 'cancelled') {
      return { label: 'Cancelled', className: 'bg-rose-100 text-rose-800 border-rose-200' };
    }
    return { label: statusStr.replace(/_/g, ' ').toUpperCase(), className: 'bg-slate-100 text-slate-800 border-slate-200' };
  };

  return (
    <div>
      <PageHeader
        title="Invoices"
        description="View all invoices, including those generated by office/admin via assisted billing on your behalf."
      />

      {exportMessage ? (
        <div className="mb-4 rounded-xl border border-cyan-200 bg-cyan-50 px-4 py-3 text-sm text-cyan-900 flex items-center justify-between">
          <span>{exportMessage}</span>
          <button type="button" onClick={() => setExportMessage(null)} className="text-xs font-semibold underline">
            Dismiss
          </button>
        </div>
      ) : null}

      <div className="mb-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-3">
        <input
          value={search}
          onChange={(event) => setSearch(event.target.value)}
          placeholder="Search invoice no"
          className="rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-cyan-500"
        />
        <select
          value={status}
          onChange={(event) => setStatus(event.target.value)}
          className="rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-cyan-500"
        >
          <option value="">All statuses</option>
          <option value="draft">Draft</option>
          <option value="posted">Posted / Unpaid</option>
          <option value="partial_paid">Partial Paid</option>
          <option value="paid">Paid</option>
          <option value="revised">Revised</option>
          <option value="cancelled">Cancelled</option>
        </select>
        <button
          type="button"
          onClick={() => {
            setSearch('');
            setStatus('');
          }}
          className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50"
        >
          Reset Filters
        </button>
      </div>

      {query.isLoading ? (
        <div className="text-sm text-slate-500">Loading invoices...</div>
      ) : query.error ? (
        <EmptyState
          title="Unable to load invoices"
          description={query.error instanceof Error ? query.error.message : 'Unknown invoice error'}
        />
      ) : rows.length === 0 ? (
        <EmptyState
          title="No invoices found"
          description="Invoices generated by the office or through delivery billing will appear here."
        />
      ) : (
        <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-slate-200 text-sm">
              <thead className="bg-slate-50 text-left text-slate-600">
                <tr>
                  <th className="px-4 py-3 font-medium">Invoice No & Date</th>
                  <th className="px-4 py-3 font-medium">Source / Billing Mode</th>
                  <th className="px-4 py-3 font-medium">Status</th>
                  <th className="px-4 py-3 font-medium text-right">Grand Total (₹)</th>
                  <th className="px-4 py-3 font-medium text-right">Outstanding (₹)</th>
                  <th className="px-4 py-3 font-medium">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 bg-white">
                {rows.map((row) => {
                  const sourceBadge = getSourceBadge(row.source);
                  const statusBadge = getStatusBadge(row.status, Number(row.outstandingAmount));
                  const isRevised = row.invoiceNo.includes('-R') || row.status === 'revised';
                  return (
                    <tr key={row.id} className="hover:bg-slate-50/75">
                      <td className="px-4 py-3 whitespace-nowrap">
                        <div className="font-medium text-slate-950 flex items-center gap-2">
                          <span>{row.invoiceNo}</span>
                          {isRevised ? (
                            <span className="rounded bg-blue-50 px-1.5 py-0.5 text-[10px] font-semibold text-blue-700 border border-blue-200">
                              REVISION
                            </span>
                          ) : null}
                        </div>
                        <div className="text-xs text-slate-500">
                          {new Date(row.invoiceDate).toLocaleDateString('en-IN')}
                          {row.dueDate ? ` (Due: ${new Date(row.dueDate).toLocaleDateString('en-IN')})` : ''}
                        </div>
                      </td>
                      <td className="px-4 py-3">
                        <span className={`inline-block rounded-full border px-2.5 py-0.5 text-xs font-medium ${sourceBadge.className}`}>
                          {sourceBadge.label}
                        </span>
                      </td>
                      <td className="px-4 py-3">
                        <span className={`inline-block rounded-full border px-2.5 py-0.5 text-xs font-medium ${statusBadge.className}`}>
                          {statusBadge.label}
                        </span>
                      </td>
                      <td className="px-4 py-3 text-right font-semibold text-slate-900 whitespace-nowrap">
                        {formatCurrency(row.grandTotal)}
                      </td>
                      <td className="px-4 py-3 text-right font-semibold text-rose-700 whitespace-nowrap">
                        {Number(row.outstandingAmount) > 0 ? formatCurrency(row.outstandingAmount) : '₹0.00'}
                      </td>
                      <td className="px-4 py-3 whitespace-nowrap">
                        <div className="flex gap-2">
                          <Link
                            href={`/portal/invoices/${row.id}`}
                            className="rounded-lg border border-slate-300 px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-100"
                          >
                            Open
                          </Link>
                          <button
                            type="button"
                            onClick={() => handleExport(row.id, row.invoiceNo, 'pdf')}
                            className="rounded-lg border border-cyan-600 bg-cyan-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-cyan-700"
                          >
                            PDF
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
          <div className="flex items-center justify-between border-t border-slate-200 px-4 py-3 text-xs text-slate-500">
            <span>
              Page {meta?.page ?? 1} of {meta?.totalPages ?? 1}
            </span>
            <span>{meta?.total ?? rows.length} invoices</span>
          </div>
        </div>
      )}
    </div>
  );
}
