'use client';

import { EmptyState } from '@/components/feedback/empty-state';
import { PageHeader } from '@/components/ui/page-header';
import { PortalApi } from '@/features/portal/api';
import { formatCurrency } from '@/lib/utils/number';
import { useQuery } from '@tanstack/react-query';
import Link from 'next/link';
import { useMemo, useState } from 'react';

export function PortalInvoicesView() {
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const queryKey = useMemo(() => ['portal', 'invoices', search, status], [search, status]);
  const query = useQuery({
    queryKey,
    queryFn: () => PortalApi.getInvoices({ page: 1, limit: 20, search: search || undefined, status: status || undefined }),
  });

  const rows = query.data?.data ?? [];
  const meta = query.data?.meta;

  return (
    <div>
      <PageHeader title="Invoices" description="View all invoices, including those generated by office/admin on your behalf." />
      <div className="mb-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-3">
        <input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search invoice no" className="rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-cyan-500" />
        <select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-cyan-500">
          <option value="">All statuses</option>
          <option value="draft">Draft</option>
          <option value="posted">Posted</option>
          <option value="partial_paid">Partial Paid</option>
          <option value="paid">Paid</option>
          <option value="cancelled">Cancelled</option>
        </select>
        <button type="button" onClick={() => { setSearch(''); setStatus(''); }} className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">Reset Filters</button>
      </div>
      {query.isLoading ? <div className="text-sm text-slate-500">Loading invoices...</div> : query.error ? <EmptyState title="Unable to load invoices" description={query.error instanceof Error ? query.error.message : 'Unknown invoice error'} /> : rows.length === 0 ? <EmptyState title="No invoices found" description="Invoices generated by the office or through delivery billing will appear here." /> : (
        <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-slate-200 text-sm">
              <thead className="bg-slate-50 text-left text-slate-600"><tr><th className="px-4 py-3 font-medium">Invoice</th><th className="px-4 py-3 font-medium">Source</th><th className="px-4 py-3 font-medium">Status</th><th className="px-4 py-3 font-medium">Total</th><th className="px-4 py-3 font-medium">Outstanding</th><th className="px-4 py-3 font-medium">Action</th></tr></thead>
              <tbody className="divide-y divide-slate-200 bg-white">
                {rows.map((row) => (
                  <tr key={row.id}><td className="px-4 py-3"><div className="font-medium text-slate-950">{row.invoiceNo}</div><div className="text-xs text-slate-500">{new Date(row.invoiceDate).toLocaleDateString('en-IN')}</div></td><td className="px-4 py-3 text-slate-700">{row.source}</td><td className="px-4 py-3 text-slate-700">{row.status}</td><td className="px-4 py-3 text-slate-700">{formatCurrency(row.grandTotal)}</td><td className="px-4 py-3 text-slate-700">{formatCurrency(row.outstandingAmount)}</td><td className="px-4 py-3"><Link href={`/portal/invoices/${row.id}`} className="rounded-lg border border-slate-300 px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-100">Open</Link></td></tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="flex items-center justify-between border-t border-slate-200 px-4 py-3 text-xs text-slate-500"><span>Page {meta?.page ?? 1} of {meta?.totalPages ?? 1}</span><span>{meta?.total ?? rows.length} invoices</span></div>
        </div>
      )}
    </div>
  );
}
